version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
